name: flutter_declarative_mdx_extensions
description: "A collection of components to customize and extend the flutter_declarative_mdx package."
version: 0.0.1
repository: https://github.com/cosella-consulting/flutter_declarative_mdx
homepage: https://cosella-consulting.github.io/flutter_declarative_mdx/

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_declarative_mdx: ^0.0.2
  flutter_hooks: ^0.21.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
