name: flutter_declarative_mdx_examples
description: "A collection of examples for use with flutter_declarative_mdx."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_declarative_mdx:
    path: ../flutter_declarative_mdx
  flutter_declarative_mdx_extensions:
    path: ../flutter_declarative_mdx_extensions
  flutter_hooks: ^0.21.2
  http: ^1.6.0
  go_router: ^16.0.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/markdown/
