name: flutter_declarative_mdx
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  google_fonts: ^6.2.1
  markdown_widget: ^2.3.2+8
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
