name: flutter_declarative_mdx
description: "flutter_declarative_mdx enables server-driven pages, forms, documents, and workflows to be defined using structured markdown and rendered directly inside a Flutter app."
version: 0.0.1
repository: https://github.com/cosella-consulting/flutter_declarative_mdx
homepage: https://cosella-consulting.github.io/flutter_declarative_mdx/

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  google_fonts: ^8.0.2
  markdown_widget: ^2.3.2+8
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
